export const TEST_ORG = {
  name: 'Test Org E2E',
  slug: 'test-org-e2e',
};

export const TEST_USERS = {
  admin: {
    email: 'admin-e2e@pulse-test.com',
    password: 'AdminE2E1234!',
    fullName: 'E2E Admin User',
    organizationName: 'E2E Test Org',
  },
  manager: {
    email: 'manager-e2e@pulse-test.com',
    password: 'ManagerE2E1234!',
    fullName: 'E2E Manager User',
    organizationName: 'E2E Test Org',
  },
  representative: {
    email: 'rep-e2e@pulse-test.com',
    password: 'RepE2E1234!',
    fullName: 'E2E Rep User',
    organizationName: 'E2E Test Org',
  },
};

export const TEST_COMPANIES = [
  {
    name: 'E2E Tech Corp',
    domain: 'e2etech.com',
    industry: 'Technology',
    employeeCount: 250,
    annualRevenue: 5000000,
    website: 'https://e2etech.com',
    email: 'info@e2etech.com',
    phone: '+1-555-0101',
    address: '123 Tech Street',
    city: 'San Francisco',
    country: 'USA',
  },
  {
    name: 'E2E Marketing Inc',
    domain: 'e2emarketing.com',
    industry: 'Marketing',
    employeeCount: 80,
    annualRevenue: 2000000,
    website: 'https://e2emarketing.com',
    email: 'hello@e2emarketing.com',
    phone: '+1-555-0102',
    address: '456 Marketing Ave',
    city: 'New York',
    country: 'USA',
  },
  {
    name: 'E2E Finance Ltd',
    domain: 'e2efinance.com',
    industry: 'Finance',
    employeeCount: 500,
    annualRevenue: 15000000,
    website: 'https://e2efinance.com',
    email: 'contact@e2efinance.com',
    phone: '+1-555-0103',
    address: '789 Finance Blvd',
    city: 'Chicago',
    country: 'USA',
  },
];

export const TEST_CONTACTS = [
  {
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@e2etech.com',
    phone: '+1-555-1001',
    jobTitle: 'CTO',
    department: 'Engineering',
    companyId: 0,
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@e2emarketing.com',
    phone: '+1-555-1002',
    jobTitle: 'VP Marketing',
    department: 'Marketing',
    companyId: 1,
  },
  {
    firstName: 'Bob',
    lastName: 'Johnson',
    email: 'bob.johnson@e2efinance.com',
    phone: '+1-555-1003',
    jobTitle: 'CFO',
    department: 'Finance',
    companyId: 2,
  },
  {
    firstName: 'Alice',
    lastName: 'Williams',
    email: 'alice.williams@e2etech.com',
    phone: '+1-555-1004',
    jobTitle: 'Engineering Manager',
    department: 'Engineering',
    companyId: 0,
  },
  {
    firstName: 'Charlie',
    lastName: 'Brown',
    email: 'charlie.brown@e2emarketing.com',
    phone: '+1-555-1005',
    jobTitle: 'Sales Director',
    department: 'Sales',
    companyId: 1,
  },
];

export const TEST_LEADS = [
  {
    title: 'E2E Enterprise Deal',
    description: 'Large enterprise opportunity for E2E Tech Corp',
    status: 'new',
    source: 'website',
    estimatedValue: 150000,
    industry: 'Technology',
    interest: 'Enterprise Plan',
    companyId: 0,
    contactId: 0,
  },
  {
    title: 'E2E Marketing Campaign',
    description: 'Marketing automation deal for E2E Marketing Inc',
    status: 'contacted',
    source: 'partner',
    estimatedValue: 50000,
    industry: 'Marketing',
    interest: 'Marketing Suite',
    companyId: 1,
    contactId: 1,
  },
  {
    title: 'E2E Finance Integration',
    description: 'Financial services integration project',
    status: 'qualified',
    source: 'linkedin',
    estimatedValue: 200000,
    industry: 'Finance',
    interest: 'API Integration',
    companyId: 2,
    contactId: 2,
  },
  {
    title: 'E2E Tech Expansion',
    description: 'Existing customer expansion for additional seats',
    status: 'proposal_sent',
    source: 'inbound',
    estimatedValue: 75000,
    industry: 'Technology',
    interest: 'Team Plan',
    companyId: 0,
    contactId: 3,
  },
  {
    title: 'E2E Lost Opportunity',
    description: 'Lead that was lost to competitor',
    status: 'lost',
    source: 'cold_call',
    estimatedValue: 30000,
    industry: 'Marketing',
    interest: 'Basic Plan',
    companyId: 1,
    contactId: 4,
  },
];

export const TEST_DEALS = [
  {
    name: 'E2E Closed Won Deal',
    description: 'Successfully closed deal with E2E Tech Corp',
    status: 'won',
    amount: 120000,
    expectedCloseDate: '2026-06-30',
    probability: 100,
    companyId: 0,
    contactId: 0,
  },
  {
    name: 'E2E Negotiation Deal',
    description: 'Deal currently in negotiation phase',
    status: 'negotiation',
    amount: 85000,
    expectedCloseDate: '2026-08-15',
    probability: 60,
    companyId: 1,
    contactId: 1,
  },
  {
    name: 'E2E Proposal Deal',
    description: 'Proposal sent, awaiting response',
    status: 'proposal',
    amount: 200000,
    expectedCloseDate: '2026-09-01',
    probability: 40,
    companyId: 2,
    contactId: 2,
  },
];

export const SEED_DATA_FILE = '.test-seed-data.json';
