"""
AISummary Model
Persists aggregated AI summaries generated by the Recent AI Summaries module.

Summary types: daily | weekly | monthly | executive | recommendation |
               risk | opportunity | performance
Periods:       today | yesterday | this_week | last_week | this_month | custom
Priority:      critical | high | medium | low
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, JSON, String, Text, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base, TenantMixin


class AISummary(Base, TenantMixin):
    """
    Persisted AI summary record.

    The `payload` JSON column stores the full structured data for the summary
    (KPIs, counts, lists, etc.) so the UI can render rich cards without
    additional DB round-trips.

    `source_modules` stores which AI modules contributed to this summary so
    we can filter / trace provenance.
    """
    __tablename__ = "ai_summaries"

    # ── Summary identity ───────────────────────────────────────────────────────
    summary_type: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True
    )
    # daily | weekly | monthly | executive | recommendation | risk | opportunity | performance

    period: Mapped[str] = mapped_column(
        String(50), nullable=False, index=True
    )
    # today | yesterday | this_week | last_week | this_month | custom

    priority: Mapped[str] = mapped_column(
        String(20), nullable=False, default="medium", index=True
    )
    # critical | high | medium | low

    # ── Content ───────────────────────────────────────────────────────────────
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    executive_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # ── Aggregated KPI counters (denormalized for fast dashboard queries) ─────
    critical_insights: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    recommendations_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    related_deals_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    related_leads_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    positive_trends: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    negative_trends: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    # ── Full rich payload ─────────────────────────────────────────────────────
    payload: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)
    # stores: kpis, related_leads, related_deals, recommendations, risks,
    #         opportunities, timeline, source-module snapshots

    # ── Source tracking ───────────────────────────────────────────────────────
    source_modules: Mapped[list] = mapped_column(
        JSON, default=list, nullable=False
    )
    # e.g. ["action_center", "pipeline_health", "going_cold", "sentiment", ...]

    # ── Timing ────────────────────────────────────────────────────────────────
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, index=True
    )
    period_start: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    period_end: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # ── Tenancy (overrides TenantMixin to add FK + index) ────────────────────
    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Ownership (optional — NULL means org-wide summary) ───────────────────
    owner_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ── Notification flag ─────────────────────────────────────────────────────
    notification_sent: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False
    )

    __table_args__ = (
        Index("ix_ai_summaries_org_generated_at", "organization_id", "generated_at"),
        Index("ix_ai_summaries_org_type_period",  "organization_id", "summary_type", "period"),
        Index("ix_ai_summaries_owner_org",         "owner_id", "organization_id"),
    )

    def __repr__(self) -> str:
        return (
            f"<AISummary id={self.id} type={self.summary_type!r} "
            f"period={self.period!r} priority={self.priority!r}>"
        )
