"""
AI-ready placeholder service.
"""
from __future__ import annotations

from datetime import datetime, timezone
from uuid import UUID, uuid4

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import NotFoundException
from app.repositories.deal_repository import DealRepository
from app.repositories.email_repository import EmailRepository
from app.repositories.lead_repository import LeadRepository
from app.schemas.ai import (
    AIConversationSummaryResponse,
    AIEmailSummaryResponse,
    AIJobResponse,
    AILeadScoreResponse,
    AINextBestActionResponse,
    AIRecommendationResponse,
    DealInsightResponse,
    SummaryResponse,
)


class AIService:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db
        self.deal_repo = DealRepository(db)
        self.lead_repo = LeadRepository(db)
        self.email_repo = EmailRepository(db)

    async def create_job(self, organization_id: UUID, job_type: str, entity_type: str, entity_id: UUID | None = None) -> AIJobResponse:
        return AIJobResponse(
            job_id=uuid4(),
            job_type=job_type,
            entity_type=entity_type,
            entity_id=entity_id,
            status="queued",
            generated_at=datetime.now(timezone.utc),
        )

    async def lead_score(self, organization_id: UUID, lead_id: UUID) -> AILeadScoreResponse:
        lead = await self.lead_repo.get_active_by_id(lead_id, organization_id)
        if not lead:
            raise NotFoundException("Lead", lead_id)
        return AILeadScoreResponse(
            lead_id=lead_id,
            status="placeholder",
            score=None,
            confidence=None,
            factors=[],
            next_best_actions=[],
            generated_at=datetime.now(timezone.utc),
        )

    async def next_best_action(self, organization_id: UUID, entity_type: str, entity_id: UUID) -> AINextBestActionResponse:
        return AINextBestActionResponse(
            entity_type=entity_type,
            entity_id=entity_id,
            status="placeholder",
            actions=[],
            rationale="AI logic will be plugged in later.",
            generated_at=datetime.now(timezone.utc),
        )

    async def conversation_summary(
        self,
        organization_id: UUID,
        thread_id: str,
    ) -> AIConversationSummaryResponse:
        return AIConversationSummaryResponse(
            thread_id=thread_id,
            status="placeholder",
            summary="Conversation summary will be generated by a future AI module.",
            bullets=[],
            generated_at=datetime.now(timezone.utc),
        )

    async def email_summary(self, organization_id: UUID, email_id: UUID) -> AIEmailSummaryResponse:
        email = await self.email_repo.get_by_id_in_org(organization_id, email_id)
        if not email:
            raise NotFoundException("Email", email_id)
        return AIEmailSummaryResponse(
            email_id=email_id,
            status="placeholder",
            summary="Email summary will be generated by a future AI module.",
            key_points=[],
            generated_at=datetime.now(timezone.utc),
        )

    async def recommendations(
        self,
        organization_id: UUID,
        entity_type: str,
        entity_id: UUID | None = None,
    ) -> AIRecommendationResponse:
        return AIRecommendationResponse(
            entity_type=entity_type,
            entity_id=entity_id,
            status="placeholder",
            recommendations=[],
            generated_at=datetime.now(timezone.utc),
        )

    async def deal_insight(self, organization_id: UUID, deal_id: UUID) -> DealInsightResponse:
        deal = await self.deal_repo.get_active_by_id(deal_id, organization_id)
        if not deal:
            raise NotFoundException("Deal", deal_id)
        return DealInsightResponse(
            deal_id=deal_id,
            status="placeholder",
            score=None,
            confidence=None,
            factors=[],
            next_best_actions=[],
            generated_at=datetime.now(timezone.utc),
        )

    async def summarize(self, organization_id: UUID, entity_type: str, prompt: str | None = None) -> SummaryResponse:
        return SummaryResponse(
            entity_type=entity_type,
            entity_id=None,
            status="placeholder",
            summary=prompt or "Summary will be generated by a future AI module.",
            bullets=[],
            generated_at=datetime.now(timezone.utc),
        )
