"""
Recommendation Service — reads stored recommendations from the database.

Recommendations are generated by the unified assessment pipeline
(run_lead_assessment → ai-service /assess). This service only reads them.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

from typing import Optional
from uuid import UUID

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.repositories.ai_repository import AIRecommendationRepository

logger = get_logger(__name__)


class RecommendationService:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db
        self.recommendation_repo = AIRecommendationRepository(db)

    async def get_for_lead(
        self, lead_id: UUID, organization_id: UUID
    ) -> Optional[dict]:
        """Get the latest stored recommendation for a lead."""
        recs = await self.recommendation_repo.latest_for_entity(
            organization_id, entity_type="lead", entity_id=lead_id
        )
        rec = recs[0] if recs else None
        if not rec:
            return None
        return {
            "recommended_action": rec.recommendation,
            "reason": rec.reasoning,
            "current_score": rec.metadata_json.get("current_score", rec.metadata_json.get("score", 0)) if rec.metadata_json else 0,
            "current_stage": rec.metadata_json.get("current_stage", rec.metadata_json.get("stage", "")) if rec.metadata_json else "",
            "all_candidates": rec.metadata_json.get("all_candidates", rec.metadata_json.get("recommendations", [])) if rec.metadata_json else [],
            "is_terminal": rec.metadata_json.get("is_terminal", False) if rec.metadata_json else False,
            "generated_at": rec.generated_at,
        }
