"""add_value_column_to_deals

Revision ID: 60e88cc272ae
Revises: 770749af2fcc
Create Date: 2026-08-10 00:03:22.690569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e88cc272ae'
down_revision: Union[str, None] = '770749af2fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_entity_id'), 'notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_entity_type'), 'notifications', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_active'), 'notifications', ['is_active'], unique=False)
    op.create_index(op.f('ix_notifications_is_dismissed'), 'notifications', ['is_dismissed'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_source_event_id'), 'notifications', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('crm_calls',
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('call_type', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_lead_id', sa.UUID(), nullable=True),
    sa.Column('related_contact_id', sa.UUID(), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_deal_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_calls_call_type'), 'crm_calls', ['call_type'], unique=False)
    op.create_index(op.f('ix_crm_calls_called_at'), 'crm_calls', ['called_at'], unique=False)
    op.create_index(op.f('ix_crm_calls_id'), 'crm_calls', ['id'], unique=False)
    op.create_index(op.f('ix_crm_calls_is_active'), 'crm_calls', ['is_active'], unique=False)
    op.create_index(op.f('ix_crm_calls_organization_id'), 'crm_calls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_calls_outcome'), 'crm_calls', ['outcome'], unique=False)
    op.create_index(op.f('ix_crm_calls_owner_id'), 'crm_calls', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_calls_priority'), 'crm_calls', ['priority'], unique=False)
    op.create_index(op.f('ix_crm_calls_related_entity_type'), 'crm_calls', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_crm_calls_related_lead_id'), 'crm_calls', ['related_lead_id'], unique=False)
    op.create_index(op.f('ix_crm_calls_status'), 'crm_calls', ['status'], unique=False)
    op.create_index(op.f('ix_crm_calls_subject'), 'crm_calls', ['subject'], unique=False)
    op.create_table('crm_emails',
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_lead_id', sa.UUID(), nullable=True),
    sa.Column('related_contact_id', sa.UUID(), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_deal_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_emails_direction'), 'crm_emails', ['direction'], unique=False)
    op.create_index(op.f('ix_crm_emails_id'), 'crm_emails', ['id'], unique=False)
    op.create_index(op.f('ix_crm_emails_is_active'), 'crm_emails', ['is_active'], unique=False)
    op.create_index(op.f('ix_crm_emails_organization_id'), 'crm_emails', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_emails_owner_id'), 'crm_emails', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_emails_priority'), 'crm_emails', ['priority'], unique=False)
    op.create_index(op.f('ix_crm_emails_related_entity_type'), 'crm_emails', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_crm_emails_related_lead_id'), 'crm_emails', ['related_lead_id'], unique=False)
    op.create_index(op.f('ix_crm_emails_sent_at'), 'crm_emails', ['sent_at'], unique=False)
    op.create_index(op.f('ix_crm_emails_status'), 'crm_emails', ['status'], unique=False)
    op.create_index(op.f('ix_crm_emails_subject'), 'crm_emails', ['subject'], unique=False)
    op.create_table('crm_notes',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_lead_id', sa.UUID(), nullable=True),
    sa.Column('related_contact_id', sa.UUID(), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_deal_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_notes_id'), 'crm_notes', ['id'], unique=False)
    op.create_index(op.f('ix_crm_notes_is_active'), 'crm_notes', ['is_active'], unique=False)
    op.create_index(op.f('ix_crm_notes_organization_id'), 'crm_notes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_notes_owner_id'), 'crm_notes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_notes_related_entity_type'), 'crm_notes', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_crm_notes_related_lead_id'), 'crm_notes', ['related_lead_id'], unique=False)
    op.create_index(op.f('ix_crm_notes_title'), 'crm_notes', ['title'], unique=False)
    op.create_table('crm_tasks',
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_lead_id', sa.UUID(), nullable=True),
    sa.Column('related_contact_id', sa.UUID(), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_deal_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_tasks_due_date'), 'crm_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_crm_tasks_id'), 'crm_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_is_active'), 'crm_tasks', ['is_active'], unique=False)
    op.create_index(op.f('ix_crm_tasks_organization_id'), 'crm_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_owner_id'), 'crm_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_priority'), 'crm_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_crm_tasks_related_entity_type'), 'crm_tasks', ['related_entity_type'], unique=False)
    op.create_index(op.f('ix_crm_tasks_related_lead_id'), 'crm_tasks', ['related_lead_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_status'), 'crm_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_crm_tasks_subject'), 'crm_tasks', ['subject'], unique=False)
    op.create_table('meetings',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meeting_link', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('reminder_minutes', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('related_lead_id', sa.UUID(), nullable=True),
    sa.Column('related_contact_id', sa.UUID(), nullable=True),
    sa.Column('related_company_id', sa.UUID(), nullable=True),
    sa.Column('related_deal_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_deal_id'], ['deals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_end_datetime'), 'meetings', ['end_datetime'], unique=False)
    op.create_index(op.f('ix_meetings_id'), 'meetings', ['id'], unique=False)
    op.create_index(op.f('ix_meetings_is_active'), 'meetings', ['is_active'], unique=False)
    op.create_index(op.f('ix_meetings_organization_id'), 'meetings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_meetings_owner_id'), 'meetings', ['owner_id'], unique=False)
    op.create_index(op.f('ix_meetings_related_company_id'), 'meetings', ['related_company_id'], unique=False)
    op.create_index(op.f('ix_meetings_related_contact_id'), 'meetings', ['related_contact_id'], unique=False)
    op.create_index(op.f('ix_meetings_related_deal_id'), 'meetings', ['related_deal_id'], unique=False)
    op.create_index(op.f('ix_meetings_related_lead_id'), 'meetings', ['related_lead_id'], unique=False)
    op.create_index(op.f('ix_meetings_start_datetime'), 'meetings', ['start_datetime'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_index(op.f('ix_meetings_title'), 'meetings', ['title'], unique=False)
    op.create_table('workflow_tasks',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('source_recommendation_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stall_count', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_recommendation_id'], ['ai_recommendations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_tasks_due_at'), 'workflow_tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_id'), 'workflow_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_is_active'), 'workflow_tasks', ['is_active'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_lead_id'), 'workflow_tasks', ['lead_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_organization_id'), 'workflow_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_source_recommendation_id'), 'workflow_tasks', ['source_recommendation_id'], unique=False)
    op.create_index(op.f('ix_workflow_tasks_status'), 'workflow_tasks', ['status'], unique=False)
    op.add_column('deals', sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('deals', sa.Column('sentiment', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_contact_id'), 'documents', ['contact_id'], unique=False)
    op.create_index(op.f('ix_documents_deal_id'), 'documents', ['deal_id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.add_column('feature_vectors', sa.Column('num_response_pairs', sa.Integer(), nullable=True))
    op.add_column('feature_vectors', sa.Column('last_processed_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feature_vectors', sa.Column('inbound_count', sa.Integer(), nullable=True))
    op.add_column('feature_vectors', sa.Column('initiated_count', sa.Integer(), nullable=True))
    op.add_column('feature_vectors', sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('feature_vectors', sa.Column('days_since_last_inbound', sa.Integer(), nullable=True))
    op.add_column('feature_vectors', sa.Column('intent', sa.String(length=100), nullable=True))
    op.add_column('feature_vectors', sa.Column('assessment_trigger', sa.String(length=50), nullable=True))
    op.add_column('feature_vectors', sa.Column('assessment_version', sa.String(length=50), nullable=True))
    op.add_column('feature_vectors', sa.Column('model_version', sa.String(length=100), nullable=True))
    op.add_column('feature_vectors', sa.Column('prompt_version', sa.String(length=100), nullable=True))
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('feature_vectors', 'prompt_version')
    op.drop_column('feature_vectors', 'model_version')
    op.drop_column('feature_vectors', 'assessment_version')
    op.drop_column('feature_vectors', 'assessment_trigger')
    op.drop_column('feature_vectors', 'intent')
    op.drop_column('feature_vectors', 'days_since_last_inbound')
    op.drop_column('feature_vectors', 'last_inbound_at')
    op.drop_column('feature_vectors', 'initiated_count')
    op.drop_column('feature_vectors', 'inbound_count')
    op.drop_column('feature_vectors', 'last_processed_sent_at')
    op.drop_column('feature_vectors', 'num_response_pairs')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_deal_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_contact_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_column('deals', 'sentiment')
    op.drop_column('deals', 'value')
    op.drop_index(op.f('ix_workflow_tasks_status'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_source_recommendation_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_organization_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_lead_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_is_active'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_id'), table_name='workflow_tasks')
    op.drop_index(op.f('ix_workflow_tasks_due_at'), table_name='workflow_tasks')
    op.drop_table('workflow_tasks')
    op.drop_index(op.f('ix_meetings_title'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_start_datetime'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_related_lead_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_related_deal_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_related_contact_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_related_company_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_owner_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_organization_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_is_active'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_end_datetime'), table_name='meetings')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_crm_tasks_subject'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_status'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_related_lead_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_related_entity_type'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_priority'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_owner_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_organization_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_is_active'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_due_date'), table_name='crm_tasks')
    op.drop_table('crm_tasks')
    op.drop_index(op.f('ix_crm_notes_title'), table_name='crm_notes')
    op.drop_index(op.f('ix_crm_notes_related_lead_id'), table_name='crm_notes')
    op.drop_index(op.f('ix_crm_notes_related_entity_type'), table_name='crm_notes')
    op.drop_index(op.f('ix_crm_notes_owner_id'), table_name='crm_notes')
    op.drop_index(op.f('ix_crm_notes_organization_id'), table_name='crm_notes')
    op.drop_index(op.f('ix_crm_notes_is_active'), table_name='crm_notes')
    op.drop_index(op.f('ix_crm_notes_id'), table_name='crm_notes')
    op.drop_table('crm_notes')
    op.drop_index(op.f('ix_crm_emails_subject'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_status'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_sent_at'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_related_lead_id'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_related_entity_type'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_priority'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_owner_id'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_organization_id'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_is_active'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_id'), table_name='crm_emails')
    op.drop_index(op.f('ix_crm_emails_direction'), table_name='crm_emails')
    op.drop_table('crm_emails')
    op.drop_index(op.f('ix_crm_calls_subject'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_status'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_related_lead_id'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_related_entity_type'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_priority'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_owner_id'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_outcome'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_organization_id'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_is_active'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_id'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_called_at'), table_name='crm_calls')
    op.drop_index(op.f('ix_crm_calls_call_type'), table_name='crm_calls')
    op.drop_table('crm_calls')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_source_event_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_dismissed'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_active'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
