"""Add LeadFeature and AI scores

Revision ID: ac74c9e9ffb1
Revises: 20260723_0010
Create Date: 2026-07-28 18:38:11.936127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac74c9e9ffb1'
down_revision: Union[str, None] = '20260723_0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversation_summaries',
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('bullets', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('regenerated_from_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regenerated_from_id'], ['ai_conversation_summaries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_summaries_email_id'), 'ai_conversation_summaries', ['email_id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_summaries_id'), 'ai_conversation_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_summaries_is_active'), 'ai_conversation_summaries', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_conversation_summaries_organization_id'), 'ai_conversation_summaries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_conversation_summaries_thread_id'), 'ai_conversation_summaries', ['thread_id'], unique=False)
    op.create_table('lead_features',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('company_size_score', sa.Float(), nullable=True),
    sa.Column('industry_complexity_score', sa.Float(), nullable=True),
    sa.Column('software_gap_score', sa.Float(), nullable=True),
    sa.Column('operational_system_score', sa.Float(), nullable=True),
    sa.Column('customization_potential_score', sa.Float(), nullable=True),
    sa.Column('response_time_score', sa.Float(), nullable=True),
    sa.Column('intent_category_score', sa.Float(), nullable=True),
    sa.Column('buying_stage_score', sa.Float(), nullable=True),
    sa.Column('customer_initiative_score', sa.Float(), nullable=True),
    sa.Column('engagement_trend_score', sa.Float(), nullable=True),
    sa.Column('decay_penalty', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_features_id'), 'lead_features', ['id'], unique=False)
    op.create_index(op.f('ix_lead_features_is_active'), 'lead_features', ['is_active'], unique=False)
    op.create_index(op.f('ix_lead_features_lead_id'), 'lead_features', ['lead_id'], unique=True)
    op.create_index(op.f('ix_lead_features_organization_id'), 'lead_features', ['organization_id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('regenerated_from_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regenerated_from_id'], ['ai_recommendations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_deal_id'), 'ai_recommendations', ['deal_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_entity_id'), 'ai_recommendations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_entity_type'), 'ai_recommendations', ['entity_type'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_id'), 'ai_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_is_active'), 'ai_recommendations', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_lead_id'), 'ai_recommendations', ['lead_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_organization_id'), 'ai_recommendations', ['organization_id'], unique=False)
    op.create_table('ai_scores',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('regenerated_from_id', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regenerated_from_id'], ['ai_scores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_scores_deal_id'), 'ai_scores', ['deal_id'], unique=False)
    op.create_index(op.f('ix_ai_scores_entity_type'), 'ai_scores', ['entity_type'], unique=False)
    op.create_index(op.f('ix_ai_scores_id'), 'ai_scores', ['id'], unique=False)
    op.create_index(op.f('ix_ai_scores_is_active'), 'ai_scores', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_scores_lead_id'), 'ai_scores', ['lead_id'], unique=False)
    op.create_index(op.f('ix_ai_scores_organization_id'), 'ai_scores', ['organization_id'], unique=False)
    op.drop_index(op.f('idx_feature_vectors_lead'), table_name='feature_vectors')
    op.drop_table('feature_vectors')
    op.drop_index(op.f('ix_activity_timeline_events_created_at'), table_name='activity_timeline_events')
    op.drop_index(op.f('ix_activity_timeline_events_org_action_created_at'), table_name='activity_timeline_events')
    op.drop_index(op.f('ix_activity_timeline_events_org_created_at'), table_name='activity_timeline_events')
    op.drop_index(op.f('ix_activity_timeline_events_org_entity_created_at'), table_name='activity_timeline_events')
    op.create_index(op.f('ix_activity_timeline_events_is_active'), 'activity_timeline_events', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.drop_constraint(op.f('fk_companies_created_by'), 'companies', type_='foreignkey')
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_contacts_is_active'), 'contacts', ['is_active'], unique=False)
    op.drop_constraint(op.f('fk_contacts_created_by'), 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_deals_amount'), table_name='deals')
    op.drop_index(op.f('ix_deals_created_at'), table_name='deals')
    op.drop_index(op.f('ix_deals_org_stage'), table_name='deals')
    op.drop_index(op.f('ix_deals_org_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_probability'), table_name='deals')
    op.drop_index(op.f('ix_deals_updated_at'), table_name='deals')
    op.create_index(op.f('ix_deals_is_active'), 'deals', ['is_active'], unique=False)
    op.drop_index(op.f('ix_domain_events_created_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_org_created_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_org_status_created_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_org_topic_status'), table_name='domain_events')
    op.create_index(op.f('ix_domain_events_is_active'), 'domain_events', ['is_active'], unique=False)
    op.drop_index(op.f('ix_emails_org_external_entity'), table_name='emails')
    op.drop_index(op.f('ix_emails_org_thread_sent_at'), table_name='emails')
    op.create_index(op.f('ix_emails_direction'), 'emails', ['direction'], unique=False)
    op.create_index(op.f('ix_emails_external_entity_id'), 'emails', ['external_entity_id'], unique=False)
    op.create_index(op.f('ix_emails_external_entity_type'), 'emails', ['external_entity_type'], unique=False)
    op.create_index(op.f('ix_emails_gmail_connection_id'), 'emails', ['gmail_connection_id'], unique=False)
    op.create_index(op.f('ix_emails_is_active'), 'emails', ['is_active'], unique=False)
    op.create_index(op.f('ix_emails_thread_id'), 'emails', ['thread_id'], unique=False)
    op.drop_constraint(op.f('emails_created_by_fkey'), 'emails', type_='foreignkey')
    op.create_index(op.f('ix_event_outbox_aggregate_id'), 'event_outbox', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_event_outbox_aggregate_type'), 'event_outbox', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_event_outbox_event_name'), 'event_outbox', ['event_name'], unique=False)
    op.create_index(op.f('ix_event_outbox_next_attempt_at'), 'event_outbox', ['next_attempt_at'], unique=False)
    op.create_index('ix_event_outbox_processing_status', 'event_outbox', ['processing_status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_gmail_connections_is_active'), 'gmail_connections', ['is_active'], unique=False)
    op.drop_constraint(op.f('gmail_connections_created_by_fkey'), 'gmail_connections', type_='foreignkey')
    op.add_column('leads', sa.Column('fit_score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('engagement_score', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('priority_tier', sa.String(length=20), nullable=True))
    op.add_column('leads', sa.Column('top_reasons', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_contact_id'), 'leads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_leads_is_active'), 'leads', ['is_active'], unique=False)
    op.create_index(op.f('ix_leads_source'), 'leads', ['source'], unique=False)
    op.drop_constraint(op.f('fk_leads_created_by'), 'leads', type_='foreignkey')
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_permissions_is_active'), 'permissions', ['is_active'], unique=False)
    op.drop_index(op.f('ix_pipeline_stages_org_probability'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_org_sort_order'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.create_index(op.f('ix_roles_is_active'), 'roles', ['is_active'], unique=False)
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_id'), 'webhook_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_is_active'), 'webhook_deliveries', ['is_active'], unique=False)
    op.drop_constraint(op.f('webhook_deliveries_created_by_fkey'), 'webhook_deliveries', type_='foreignkey')
    op.create_index(op.f('ix_webhook_endpoints_id'), 'webhook_endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_is_active'), 'webhook_endpoints', ['is_active'], unique=False)
    op.drop_constraint(op.f('webhook_endpoints_created_by_fkey'), 'webhook_endpoints', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('webhook_endpoints_created_by_fkey'), 'webhook_endpoints', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_webhook_endpoints_is_active'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_id'), table_name='webhook_endpoints')
    op.create_foreign_key(op.f('webhook_deliveries_created_by_fkey'), 'webhook_deliveries', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_webhook_deliveries_is_active'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.drop_index(op.f('ix_roles_is_active'), table_name='roles')
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_org_sort_order'), 'pipeline_stages', ['organization_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_org_probability'), 'pipeline_stages', ['organization_id', 'probability'], unique=False)
    op.drop_index(op.f('ix_permissions_is_active'), table_name='permissions')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.create_foreign_key(op.f('fk_leads_created_by'), 'leads', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_leads_source'), table_name='leads')
    op.drop_index(op.f('ix_leads_is_active'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_column('leads', 'top_reasons')
    op.drop_column('leads', 'priority_tier')
    op.drop_column('leads', 'engagement_score')
    op.drop_column('leads', 'fit_score')
    op.create_foreign_key(op.f('gmail_connections_created_by_fkey'), 'gmail_connections', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_gmail_connections_is_active'), table_name='gmail_connections')
    op.drop_index('ix_event_outbox_processing_status', table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_next_attempt_at'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_event_name'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_aggregate_type'), table_name='event_outbox')
    op.drop_index(op.f('ix_event_outbox_aggregate_id'), table_name='event_outbox')
    op.create_foreign_key(op.f('emails_created_by_fkey'), 'emails', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_emails_thread_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_is_active'), table_name='emails')
    op.drop_index(op.f('ix_emails_gmail_connection_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_external_entity_type'), table_name='emails')
    op.drop_index(op.f('ix_emails_external_entity_id'), table_name='emails')
    op.drop_index(op.f('ix_emails_direction'), table_name='emails')
    op.create_index(op.f('ix_emails_org_thread_sent_at'), 'emails', ['organization_id', 'thread_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_emails_org_external_entity'), 'emails', ['organization_id', 'external_entity_type', 'external_entity_id'], unique=False)
    op.drop_index(op.f('ix_domain_events_is_active'), table_name='domain_events')
    op.create_index(op.f('ix_domain_events_org_topic_status'), 'domain_events', ['organization_id', 'topic', 'status'], unique=False)
    op.create_index(op.f('ix_domain_events_org_status_created_at'), 'domain_events', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_domain_events_org_created_at'), 'domain_events', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_domain_events_created_at'), 'domain_events', ['created_at'], unique=False)
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_index(op.f('ix_deals_is_active'), table_name='deals')
    op.create_index(op.f('ix_deals_updated_at'), 'deals', ['updated_at'], unique=False)
    op.create_index(op.f('ix_deals_probability'), 'deals', ['probability'], unique=False)
    op.create_index(op.f('ix_deals_org_status'), 'deals', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_deals_org_stage'), 'deals', ['organization_id', 'pipeline_stage_id'], unique=False)
    op.create_index(op.f('ix_deals_created_at'), 'deals', ['created_at'], unique=False)
    op.create_index(op.f('ix_deals_amount'), 'deals', ['amount'], unique=False)
    op.create_foreign_key(op.f('fk_contacts_created_by'), 'contacts', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_contacts_is_active'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.create_foreign_key(op.f('fk_companies_created_by'), 'companies', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_index(op.f('ix_activity_timeline_events_is_active'), table_name='activity_timeline_events')
    op.create_index(op.f('ix_activity_timeline_events_org_entity_created_at'), 'activity_timeline_events', ['organization_id', 'entity_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_timeline_events_org_created_at'), 'activity_timeline_events', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_timeline_events_org_action_created_at'), 'activity_timeline_events', ['organization_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_timeline_events_created_at'), 'activity_timeline_events', ['created_at'], unique=False)
    op.create_table('feature_vectors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feature_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('company_size_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('industry_complexity_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operational_system_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('software_gap_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customization_potential_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_response_time', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('response_time_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reply_recency_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('days_since_last_outbound', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement_decay_penalty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_initiative_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buying_stage_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('intent_strength_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('engagement_trend_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ai_intent_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_intent_category_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('feature_vectors_lead_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('feature_vectors_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('feature_vectors_pkey')),
    sa.UniqueConstraint('lead_id', 'feature_version', 'generated_at', name=op.f('uq_feature_vectors_lead_version_generated_at'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_feature_vectors_lead'), 'feature_vectors', ['lead_id'], unique=False)
    op.drop_index(op.f('ix_ai_scores_organization_id'), table_name='ai_scores')
    op.drop_index(op.f('ix_ai_scores_lead_id'), table_name='ai_scores')
    op.drop_index(op.f('ix_ai_scores_is_active'), table_name='ai_scores')
    op.drop_index(op.f('ix_ai_scores_id'), table_name='ai_scores')
    op.drop_index(op.f('ix_ai_scores_entity_type'), table_name='ai_scores')
    op.drop_index(op.f('ix_ai_scores_deal_id'), table_name='ai_scores')
    op.drop_table('ai_scores')
    op.drop_index(op.f('ix_ai_recommendations_organization_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_lead_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_is_active'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_entity_type'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_entity_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_deal_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_lead_features_organization_id'), table_name='lead_features')
    op.drop_index(op.f('ix_lead_features_lead_id'), table_name='lead_features')
    op.drop_index(op.f('ix_lead_features_is_active'), table_name='lead_features')
    op.drop_index(op.f('ix_lead_features_id'), table_name='lead_features')
    op.drop_table('lead_features')
    op.drop_index(op.f('ix_ai_conversation_summaries_thread_id'), table_name='ai_conversation_summaries')
    op.drop_index(op.f('ix_ai_conversation_summaries_organization_id'), table_name='ai_conversation_summaries')
    op.drop_index(op.f('ix_ai_conversation_summaries_is_active'), table_name='ai_conversation_summaries')
    op.drop_index(op.f('ix_ai_conversation_summaries_id'), table_name='ai_conversation_summaries')
    op.drop_index(op.f('ix_ai_conversation_summaries_email_id'), table_name='ai_conversation_summaries')
    op.drop_table('ai_conversation_summaries')
    # ### end Alembic commands ###
