"""add job_title to leads

Revision ID: e31deca35779
Revises: 202607300003
Create Date: 2026-07-30 14:40:40.814972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31deca35779'
down_revision = '202607300003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_summaries',
    sa.Column('summary_type', sa.String(length=50), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('critical_insights', sa.Integer(), nullable=False),
    sa.Column('recommendations_count', sa.Integer(), nullable=False),
    sa.Column('related_deals_count', sa.Integer(), nullable=False),
    sa.Column('related_leads_count', sa.Integer(), nullable=False),
    sa.Column('positive_trends', sa.Integer(), nullable=False),
    sa.Column('negative_trends', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('source_modules', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_summaries_generated_at'), 'ai_summaries', ['generated_at'], unique=False)
    op.create_index(op.f('ix_ai_summaries_id'), 'ai_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_is_active'), 'ai_summaries', ['is_active'], unique=False)
    op.create_index('ix_ai_summaries_org_generated_at', 'ai_summaries', ['organization_id', 'generated_at'], unique=False)
    op.create_index('ix_ai_summaries_org_type_period', 'ai_summaries', ['organization_id', 'summary_type', 'period'], unique=False)
    op.create_index(op.f('ix_ai_summaries_organization_id'), 'ai_summaries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_owner_id'), 'ai_summaries', ['owner_id'], unique=False)
    op.create_index('ix_ai_summaries_owner_org', 'ai_summaries', ['owner_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_period'), 'ai_summaries', ['period'], unique=False)
    op.create_index(op.f('ix_ai_summaries_priority'), 'ai_summaries', ['priority'], unique=False)
    op.create_index(op.f('ix_ai_summaries_summary_type'), 'ai_summaries', ['summary_type'], unique=False)
    op.create_foreign_key(None, 'deals', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('leads', sa.Column('job_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'job_title')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_index(op.f('ix_ai_summaries_summary_type'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_priority'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_period'), table_name='ai_summaries')
    op.drop_index('ix_ai_summaries_owner_org', table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_owner_id'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_organization_id'), table_name='ai_summaries')
    op.drop_index('ix_ai_summaries_org_type_period', table_name='ai_summaries')
    op.drop_index('ix_ai_summaries_org_generated_at', table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_is_active'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_id'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_generated_at'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    # ### end Alembic commands ###
